### ISSUE TITLE
LED Dimming not working correctly

### ISSUE THREAD

**Issue by baaragdata** [PiSupply/Bright-Pi#14] opened 2020-01-22 11:14 UTC
I am using the BrightPi on an NVIDIA Jetson Nano and it works pretty well. Although I have encountered a problem and am not sure yet where it is coming from.

When I set the dim value for LEDs sometimes this value is ignored and the LED will come on far brighter than I have set it. When I issue the get dim command the value looks correct.

Only a power cycle of the BrightPi board seems to resolve things. I have searched for trouble with the SC620 but there is almost nothing (other than the datasheet) on this, and certainly nobody complaining about what I am experiencing. 

I will try and get a script together to replicate the problem.

I will also try it on a Raspi, just in case it is a Jetson I2C foible.

**Comment by baaragdata** [comment] 2020-01-22 11:26
I just checked using the raw I2C commands and all works fine.

When I send this command with the LED on the LED will change instantly. If it is off then it will come on at that level the next time I switch it on. In other words it is not the I2C....the problem lies elsewhere.

 i2cset -y 1 0x70 0x07 0x01

**Comment by baaragdata** [comment] 2020-01-22 11:38
I found the bug.

Line 102 in brightpilib.py
`self._bus.write_byte_data(BrightPi._device_address, led, self._led_dim[led - 1])`

should be.....
`self._bus.write_byte_data(BrightPi._device_address, self._led_hex[led - 1], self._led_dim[led - 1])`

**Comment by shawaj** [comment] 2020-01-22 11:54
Thanks very much. Would you mind submitting this as a pull request?

**Comment by baaragdata** [comment] 2020-01-22 13:29
I'm afraid I am not sure how....it's about as clear as mud!

**Comment by shawaj** [comment] 2020-01-22 14:05
@baaragdata you just go to the file on our GitHub, click the little edit pencil at the top right of the file, make the edits, submit the commit at the bottom, and then it'll guide you through the PR process. There is other ways for bigger edits which are easier. But for a basic one that tends to be the easiest in my opinion.

If you don't have the time, I can do it for you though, no problem at all. Just thought you might be keen to know :-)

Let me know either way

**Comment by shawaj** [comment] 2020-01-22 14:14
@ChristopherRush can you give #15 a quick test before we merge.

Can't see any issues with it but just so we've tested it

**Comment by ChristopherRush** [comment] 2020-01-22 14:15
Yes will test and commit.

**Comment by baaragdata** [comment] 2020-01-22 16:00
I had to re-read the datasheet and then it all made sense. All tested and working now.

**Comment by baaragdata** [comment] 2020-01-23 11:39
Sorry - I couldn't find my last change so I posted it again. Now it seems there are 3 patches. I hope you can sort it out.

Just to let you know I am now using it in a Jetson project and all is working fine.

Thanks for a nice neat product. 👍

**Comment by theyosh** [comment] 2020-07-17 12:20
Hello, when will the PR merged? As I can confirm the same bug here with a Raspberry PI.

If you use the variable LED_WHITE for just on and off, the 4 white leds go on and off. But when you use the set_led_dim you need a different list of LEDS. Then it turns out that you need LED2,LED4,LED5,LED7 which is different then the list of LED_WHITE.

After manual applying the PR, it works like expected. So I was wondering when this PR will be merged?

**Comment by tvoverbeek** [comment] 2020-07-21 13:13
PR has been merged. Closing Issue

**Closed as completed by tvoverbeek** 2020-07-21 13:13 UTC
